linters:
  disable-all: true
  enable:
    - gofmt
    - bodyclose
    - depguard
    - dogsled
#    - dupl
#    - errcheck
    - exportloopref
#    - funlen
    - gochecknoinits
#    - goconst
#    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
#    - lll
    - misspell
    - nakedret
    - noctx
#    - nolintlint
    - staticcheck
#    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace