// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/chartmogul/chartmogul-go (interfaces: IApi)

package mock_chartmogul_go

import (
	chartmogul_go "github.com/chartmogul/chartmogul-go"
	gomock "github.com/golang/mock/gomock"
)

// Mock of IApi interface
type MockIApi struct {
	ctrl     *gomock.Controller
	recorder *_MockIApiRecorder
}

// Recorder for MockIApi (not exported)
type _MockIApiRecorder struct {
	mock *MockIApi
}

func NewMockIApi(ctrl *gomock.Controller) *MockIApi {
	mock := &MockIApi{ctrl: ctrl}
	mock.recorder = &_MockIApiRecorder{mock}
	return mock
}

func (_m *MockIApi) EXPECT() *_MockIApiRecorder {
	return _m.recorder
}

func (_m *MockIApi) AddCustomAttributesToCustomer(_param0 string, _param1 []*chartmogul_go.CustomAttribute) (*chartmogul_go.CustomAttributes, error) {
	ret := _m.ctrl.Call(_m, "AddCustomAttributesToCustomer", _param0, _param1)
	ret0, _ := ret[0].(*chartmogul_go.CustomAttributes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) AddCustomAttributesToCustomer(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AddCustomAttributesToCustomer", arg0, arg1)
}

func (_m *MockIApi) AddCustomAttributesWithEmail(_param0 string, _param1 []*chartmogul_go.CustomAttribute) (*chartmogul_go.Customers, error) {
	ret := _m.ctrl.Call(_m, "AddCustomAttributesWithEmail", _param0, _param1)
	ret0, _ := ret[0].(*chartmogul_go.Customers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) AddCustomAttributesWithEmail(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AddCustomAttributesWithEmail", arg0, arg1)
}

func (_m *MockIApi) AddTagsToCustomer(_param0 string, _param1 []string) (*chartmogul_go.TagsResult, error) {
	ret := _m.ctrl.Call(_m, "AddTagsToCustomer", _param0, _param1)
	ret0, _ := ret[0].(*chartmogul_go.TagsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) AddTagsToCustomer(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AddTagsToCustomer", arg0, arg1)
}

func (_m *MockIApi) AddTagsToCustomersWithEmail(_param0 string, _param1 []string) (*chartmogul_go.Customers, error) {
	ret := _m.ctrl.Call(_m, "AddTagsToCustomersWithEmail", _param0, _param1)
	ret0, _ := ret[0].(*chartmogul_go.Customers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) AddTagsToCustomersWithEmail(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AddTagsToCustomersWithEmail", arg0, arg1)
}

func (_m *MockIApi) CancelSubscription(_param0 string, _param1 *chartmogul_go.CancelSubscriptionParams) (*chartmogul_go.Subscription, error) {
	ret := _m.ctrl.Call(_m, "CancelSubscription", _param0, _param1)
	ret0, _ := ret[0].(*chartmogul_go.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) CancelSubscription(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CancelSubscription", arg0, arg1)
}

func (_m *MockIApi) CreateCustomer(_param0 *chartmogul_go.NewCustomer) (*chartmogul_go.Customer, error) {
	ret := _m.ctrl.Call(_m, "CreateCustomer", _param0)
	ret0, _ := ret[0].(*chartmogul_go.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) CreateCustomer(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateCustomer", arg0)
}

func (_m *MockIApi) CreateDataSource(_param0 string) (*chartmogul_go.DataSource, error) {
	ret := _m.ctrl.Call(_m, "CreateDataSource", _param0)
	ret0, _ := ret[0].(*chartmogul_go.DataSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) CreateDataSource(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateDataSource", arg0)
}

func (_m *MockIApi) CreateInvoices(_param0 []*chartmogul_go.Invoice, _param1 string) (*chartmogul_go.Invoices, error) {
	ret := _m.ctrl.Call(_m, "CreateInvoices", _param0, _param1)
	ret0, _ := ret[0].(*chartmogul_go.Invoices)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) CreateInvoices(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateInvoices", arg0, arg1)
}

func (_m *MockIApi) CreatePlan(_param0 *chartmogul_go.Plan) (*chartmogul_go.Plan, error) {
	ret := _m.ctrl.Call(_m, "CreatePlan", _param0)
	ret0, _ := ret[0].(*chartmogul_go.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) CreatePlan(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreatePlan", arg0)
}

func (_m *MockIApi) CreateTransaction(_param0 *chartmogul_go.Transaction, _param1 string) (*chartmogul_go.Transaction, error) {
	ret := _m.ctrl.Call(_m, "CreateTransaction", _param0, _param1)
	ret0, _ := ret[0].(*chartmogul_go.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) CreateTransaction(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateTransaction", arg0, arg1)
}

func (_m *MockIApi) DeleteCustomer(_param0 string) error {
	ret := _m.ctrl.Call(_m, "DeleteCustomer", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockIApiRecorder) DeleteCustomer(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteCustomer", arg0)
}

func (_m *MockIApi) DeleteCustomerInvoices(_param0 string, _param1 string) error {
	ret := _m.ctrl.Call(_m, "DeleteCustomerInvoices", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockIApiRecorder) DeleteCustomerInvoices(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteCustomerInvoices", arg0, arg1)
}

func (_m *MockIApi) DeleteDataSource(_param0 string) error {
	ret := _m.ctrl.Call(_m, "DeleteDataSource", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockIApiRecorder) DeleteDataSource(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteDataSource", arg0)
}

func (_m *MockIApi) DeleteInvoice(_param0 string) error {
	ret := _m.ctrl.Call(_m, "DeleteInvoice", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockIApiRecorder) DeleteInvoice(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteInvoice", arg0)
}

func (_m *MockIApi) DeletePlan(_param0 string) error {
	ret := _m.ctrl.Call(_m, "DeletePlan", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockIApiRecorder) DeletePlan(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeletePlan", arg0)
}

func (_m *MockIApi) ListAllInvoices(_param0 *chartmogul_go.ListAllInvoicesParams) (*chartmogul_go.Invoices, error) {
	ret := _m.ctrl.Call(_m, "ListAllInvoices", _param0)
	ret0, _ := ret[0].(*chartmogul_go.Invoices)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) ListAllInvoices(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListAllInvoices", arg0)
}

func (_m *MockIApi) ListCustomers(_param0 *chartmogul_go.ListCustomersParams) (*chartmogul_go.Customers, error) {
	ret := _m.ctrl.Call(_m, "ListCustomers", _param0)
	ret0, _ := ret[0].(*chartmogul_go.Customers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) ListCustomers(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListCustomers", arg0)
}

func (_m *MockIApi) ListDataSources() (*chartmogul_go.DataSources, error) {
	ret := _m.ctrl.Call(_m, "ListDataSources")
	ret0, _ := ret[0].(*chartmogul_go.DataSources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) ListDataSources() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListDataSources")
}

func (_m *MockIApi) ListInvoices(_param0 *chartmogul_go.Cursor, _param1 string) (*chartmogul_go.Invoices, error) {
	ret := _m.ctrl.Call(_m, "ListInvoices", _param0, _param1)
	ret0, _ := ret[0].(*chartmogul_go.Invoices)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) ListInvoices(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListInvoices", arg0, arg1)
}

func (_m *MockIApi) ListPlans(_param0 *chartmogul_go.ListPlansParams) (*chartmogul_go.Plans, error) {
	ret := _m.ctrl.Call(_m, "ListPlans", _param0)
	ret0, _ := ret[0].(*chartmogul_go.Plans)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) ListPlans(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListPlans", arg0)
}

func (_m *MockIApi) ListSubscriptions(_param0 *chartmogul_go.Cursor, _param1 string) (*chartmogul_go.Subscriptions, error) {
	ret := _m.ctrl.Call(_m, "ListSubscriptions", _param0, _param1)
	ret0, _ := ret[0].(*chartmogul_go.Subscriptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) ListSubscriptions(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListSubscriptions", arg0, arg1)
}

func (_m *MockIApi) MergeCustomers(_param0 *chartmogul_go.MergeCustomersParams) error {
	ret := _m.ctrl.Call(_m, "MergeCustomers", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockIApiRecorder) MergeCustomers(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MergeCustomers", arg0)
}

func (_m *MockIApi) MetricsListActivities(_param0 *chartmogul_go.Cursor, _param1 string) (*chartmogul_go.MetricsActivities, error) {
	ret := _m.ctrl.Call(_m, "MetricsListActivities", _param0, _param1)
	ret0, _ := ret[0].(*chartmogul_go.MetricsActivities)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) MetricsListActivities(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MetricsListActivities", arg0, arg1)
}

func (_m *MockIApi) MetricsListSubscriptions(_param0 *chartmogul_go.Cursor, _param1 string) (*chartmogul_go.MetricsSubscriptions, error) {
	ret := _m.ctrl.Call(_m, "MetricsListSubscriptions", _param0, _param1)
	ret0, _ := ret[0].(*chartmogul_go.MetricsSubscriptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) MetricsListSubscriptions(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MetricsListSubscriptions", arg0, arg1)
}

func (_m *MockIApi) MetricsRetrieveARPA(_param0 *chartmogul_go.MetricsFilter) (*chartmogul_go.ARPAResult, error) {
	ret := _m.ctrl.Call(_m, "MetricsRetrieveARPA", _param0)
	ret0, _ := ret[0].(*chartmogul_go.ARPAResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) MetricsRetrieveARPA(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MetricsRetrieveARPA", arg0)
}

func (_m *MockIApi) MetricsRetrieveARR(_param0 *chartmogul_go.MetricsFilter) (*chartmogul_go.ARRResult, error) {
	ret := _m.ctrl.Call(_m, "MetricsRetrieveARR", _param0)
	ret0, _ := ret[0].(*chartmogul_go.ARRResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) MetricsRetrieveARR(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MetricsRetrieveARR", arg0)
}

func (_m *MockIApi) MetricsRetrieveASP(_param0 *chartmogul_go.MetricsFilter) (*chartmogul_go.ASPResult, error) {
	ret := _m.ctrl.Call(_m, "MetricsRetrieveASP", _param0)
	ret0, _ := ret[0].(*chartmogul_go.ASPResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) MetricsRetrieveASP(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MetricsRetrieveASP", arg0)
}

func (_m *MockIApi) MetricsRetrieveAll(_param0 *chartmogul_go.MetricsFilter) (*chartmogul_go.MetricsResult, error) {
	ret := _m.ctrl.Call(_m, "MetricsRetrieveAll", _param0)
	ret0, _ := ret[0].(*chartmogul_go.MetricsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) MetricsRetrieveAll(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MetricsRetrieveAll", arg0)
}

func (_m *MockIApi) MetricsRetrieveCustomerChurnRate(_param0 *chartmogul_go.MetricsFilter) (*chartmogul_go.CustomerChurnRateResult, error) {
	ret := _m.ctrl.Call(_m, "MetricsRetrieveCustomerChurnRate", _param0)
	ret0, _ := ret[0].(*chartmogul_go.CustomerChurnRateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) MetricsRetrieveCustomerChurnRate(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MetricsRetrieveCustomerChurnRate", arg0)
}

func (_m *MockIApi) MetricsRetrieveCustomerCount(_param0 *chartmogul_go.MetricsFilter) (*chartmogul_go.CustomerCountResult, error) {
	ret := _m.ctrl.Call(_m, "MetricsRetrieveCustomerCount", _param0)
	ret0, _ := ret[0].(*chartmogul_go.CustomerCountResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) MetricsRetrieveCustomerCount(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MetricsRetrieveCustomerCount", arg0)
}

func (_m *MockIApi) MetricsRetrieveLTV(_param0 *chartmogul_go.MetricsFilter) (*chartmogul_go.LTVResult, error) {
	ret := _m.ctrl.Call(_m, "MetricsRetrieveLTV", _param0)
	ret0, _ := ret[0].(*chartmogul_go.LTVResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) MetricsRetrieveLTV(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MetricsRetrieveLTV", arg0)
}

func (_m *MockIApi) MetricsRetrieveMRR(_param0 *chartmogul_go.MetricsFilter) (*chartmogul_go.MRRResult, error) {
	ret := _m.ctrl.Call(_m, "MetricsRetrieveMRR", _param0)
	ret0, _ := ret[0].(*chartmogul_go.MRRResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) MetricsRetrieveMRR(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MetricsRetrieveMRR", arg0)
}

func (_m *MockIApi) MetricsRetrieveMRRChurnRate(_param0 *chartmogul_go.MetricsFilter) (*chartmogul_go.MRRChurnRateResult, error) {
	ret := _m.ctrl.Call(_m, "MetricsRetrieveMRRChurnRate", _param0)
	ret0, _ := ret[0].(*chartmogul_go.MRRChurnRateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) MetricsRetrieveMRRChurnRate(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MetricsRetrieveMRRChurnRate", arg0)
}

func (_m *MockIApi) Ping() (bool, error) {
	ret := _m.ctrl.Call(_m, "Ping")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) Ping() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Ping")
}

func (_m *MockIApi) PurgeDataSource(_param0 string) error {
	ret := _m.ctrl.Call(_m, "PurgeDataSource", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockIApiRecorder) PurgeDataSource(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PurgeDataSource", arg0)
}

func (_m *MockIApi) RemoveCustomAttributes(_param0 string, _param1 []string) (*chartmogul_go.CustomAttributes, error) {
	ret := _m.ctrl.Call(_m, "RemoveCustomAttributes", _param0, _param1)
	ret0, _ := ret[0].(*chartmogul_go.CustomAttributes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) RemoveCustomAttributes(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RemoveCustomAttributes", arg0, arg1)
}

func (_m *MockIApi) RemoveTagsFromCustomer(_param0 string, _param1 []string) (*chartmogul_go.TagsResult, error) {
	ret := _m.ctrl.Call(_m, "RemoveTagsFromCustomer", _param0, _param1)
	ret0, _ := ret[0].(*chartmogul_go.TagsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) RemoveTagsFromCustomer(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RemoveTagsFromCustomer", arg0, arg1)
}

func (_m *MockIApi) RetrieveCustomer(_param0 string) (*chartmogul_go.Customer, error) {
	ret := _m.ctrl.Call(_m, "RetrieveCustomer", _param0)
	ret0, _ := ret[0].(*chartmogul_go.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) RetrieveCustomer(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RetrieveCustomer", arg0)
}

func (_m *MockIApi) RetrieveCustomersAttributes(_param0 string) (*chartmogul_go.Attributes, error) {
	ret := _m.ctrl.Call(_m, "RetrieveCustomersAttributes", _param0)
	ret0, _ := ret[0].(*chartmogul_go.Attributes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) RetrieveCustomersAttributes(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RetrieveCustomersAttributes", arg0)
}

func (_m *MockIApi) RetrieveDataSource(_param0 string) (*chartmogul_go.DataSource, error) {
	ret := _m.ctrl.Call(_m, "RetrieveDataSource", _param0)
	ret0, _ := ret[0].(*chartmogul_go.DataSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) RetrieveDataSource(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RetrieveDataSource", arg0)
}

func (_m *MockIApi) RetrieveInvoice(_param0 string) (*chartmogul_go.Invoice, error) {
	ret := _m.ctrl.Call(_m, "RetrieveInvoice", _param0)
	ret0, _ := ret[0].(*chartmogul_go.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) RetrieveInvoice(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RetrieveInvoice", arg0)
}

func (_m *MockIApi) RetrievePlan(_param0 string) (*chartmogul_go.Plan, error) {
	ret := _m.ctrl.Call(_m, "RetrievePlan", _param0)
	ret0, _ := ret[0].(*chartmogul_go.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) RetrievePlan(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RetrievePlan", arg0)
}

func (_m *MockIApi) SearchCustomers(_param0 *chartmogul_go.SearchCustomersParams) (*chartmogul_go.Customers, error) {
	ret := _m.ctrl.Call(_m, "SearchCustomers", _param0)
	ret0, _ := ret[0].(*chartmogul_go.Customers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) SearchCustomers(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SearchCustomers", arg0)
}

func (_m *MockIApi) UpdateCustomAttributesOfCustomer(_param0 string, _param1 map[string]interface{}) (*chartmogul_go.CustomAttributes, error) {
	ret := _m.ctrl.Call(_m, "UpdateCustomAttributesOfCustomer", _param0, _param1)
	ret0, _ := ret[0].(*chartmogul_go.CustomAttributes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) UpdateCustomAttributesOfCustomer(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateCustomAttributesOfCustomer", arg0, arg1)
}

func (_m *MockIApi) UpdateCustomer(_param0 *chartmogul_go.Customer, _param1 string) (*chartmogul_go.Customer, error) {
	ret := _m.ctrl.Call(_m, "UpdateCustomer", _param0, _param1)
	ret0, _ := ret[0].(*chartmogul_go.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) UpdateCustomer(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateCustomer", arg0, arg1)
}

func (_m *MockIApi) UpdatePlan(_param0 *chartmogul_go.Plan, _param1 string) (*chartmogul_go.Plan, error) {
	ret := _m.ctrl.Call(_m, "UpdatePlan", _param0, _param1)
	ret0, _ := ret[0].(*chartmogul_go.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockIApiRecorder) UpdatePlan(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdatePlan", arg0, arg1)
}
