name: Run specs and generate Code Climate report
on:
  push:
    branches: [ main, 'v*' ]
  pull_request:
    branches: [ main, 'v*' ]
permissions:
  contents: read
  pull-requests: read
jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go-versions: ['1.21', '1.22', '1.23', '1.24']
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Go ${{ matrix.go-versions }}
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: ${{ matrix.go-versions }}

      - name: Run tests
        run: make test

  code-coverage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: '1.24'

      - name: Set ENV for codeclimate (pull_request)
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/$GITHUB_HEAD_REF:refs/remotes/origin/$GITHUB_HEAD_REF
          echo "GIT_BRANCH=$GITHUB_HEAD_REF" >> $GITHUB_ENV
          echo "GIT_COMMIT_SHA=$(git rev-parse origin/$GITHUB_HEAD_REF)" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'

      - name: Run test coverage
        run: |
            for pkg in $(go list ./... | grep -v vendor); do
                go test -coverprofile=$(echo $pkg | tr / -).cover $pkg
            done
            echo "mode: set" > c.out
            grep -h -v "^mode:" ./*.cover >> c.out
            rm -f *.cover
            MODULE=$(go list -m)
            sed -i "s#^${MODULE}/##g" c.out
  linter:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: '1.24'

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6.5.2
        with:
          version: 'v1.64.8'
          only-new-issues: true
